# Generated by Django 4.2.4 on 2023-08-18 01:18

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cliente_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cliente_cpf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('cliente_endereco', models.CharField(max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name_plural': 'Cadastro de Cliente',
            },
        ),
        migrations.CreateModel(
            name='GrupoPecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_pecas', models.CharField(max_length=20, verbose_name='Nome do Grupo')),
                ('grupo_description', models.TextField(blank=True, verbose_name='Descrição do grupo cadastrado')),
            ],
            options={
                'verbose_name_plural': 'Cadastro de Grupo de Peças',
            },
        ),
        migrations.CreateModel(
            name='PecasVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pecas_veiculo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Cadastro de Peças',
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVeiculo', models.CharField(max_length=20, verbose_name='Tipo de veículo')),
            ],
            options={
                'verbose_name_plural': 'Cadastro de Veículo',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo_data', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('veiculo_placa', models.CharField(max_length=10, unique=True, verbose_name='Placa do veículo')),
                ('veiculo_operante', models.BooleanField(default=False)),
                ('veiculo_descricao', models.TextField(blank=True, verbose_name='Descrição do Veículo')),
                ('veiculo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('veiculo_grupo_pecas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.grupopecas', verbose_name='Grupo de peças associado')),
                ('veiculo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.tipoveiculo')),
            ],
            options={
                'verbose_name_plural': 'Veículo',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_codigo', models.IntegerField(editable=False, unique=True, verbose_name='Código')),
                ('ordem_data', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('ordem_data_atualizada', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('ordem_classificacao', models.BooleanField(default=False, verbose_name='Ordem aberta?')),
                ('ordem_descricao', models.TextField(blank=True, verbose_name='Descrição do procedimento')),
                ('ordem_troca', models.BooleanField(default=False, verbose_name='Troca de peça?')),
                ('ordem_valor_servico', models.IntegerField(default=0, verbose_name='Valor do serviço')),
                ('ordem_peca', models.IntegerField(default=0, verbose_name='Valor da peça')),
                ('ordem_valor', models.IntegerField(default=0, verbose_name='Outros Gastos')),
                ('ordem_outros', models.TextField(blank=True, max_length=40, verbose_name='Descrição dos gastos')),
                ('ordem_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente associado')),
                ('ordem_grupo_pecas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.grupopecas', verbose_name='Grupo de peças')),
                ('ordem_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.veiculo', to_field='veiculo_placa', verbose_name='Placa do veículo')),
                ('pecas_grupo', models.ManyToManyField(blank=True, to='clientes.pecasveiculo', verbose_name='Peças do Grupo')),
            ],
            options={
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.AddField(
            model_name='grupopecas',
            name='pecas_veiculo',
            field=models.ManyToManyField(to='clientes.pecasveiculo', verbose_name='Peças a serem adicionadas'),
        ),
    ]
